apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::254103026944:role/eksctl-expense-2-nodegroup-expense-NodeInstanceRole-KgrGd5JpIKhU
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
     - groups:
       - expense-pod-reader
       userarn: arn:aws:iam::254103026944:user/chandra
       username: chandra
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-02T07:05:18Z"
  name: aws-auth
  namespace: kube-system
  uid: 7fb59517-dc7a-4c32-8b21-8d497c9bd08e # don't delete this line, this is uniqu ID
