apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::254103026944:role/eksctl-expense-2-nodegroup-expense-NodeInstanceRole-jLEa8e92bbhJ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}} 
  mapUsers: |
    - userarn: arn:aws:iam::254103026944:user/srinu
      username: srinu
      groups:
      - expense-pod-reader

kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-02T10:26:37Z"
  name: aws-auth
  namespace: kube-system
  uid: 1e1bf0d4-303e-4ee3-b14b-16bce0ec8fdf # don't dlete this one, it is uniqe ID
